# Herdr configuration
# https://herdr.dev/docs/configuration

[terminal]
default_shell = "zsh"
new_cwd = "follow"

[theme]
name = "catppuccin"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin"

[keys]
prefix = "ctrl+b"

[[keys.command]]
key = "prefix+alt+g"
type = "pane"
command = "lazygit"
description = "run lazygit"

[ui]
sidebar_width = 32
mouse_capture = true
confirm_close = true
pane_borders = true
pane_gaps = true

[ui.toast]
delivery = "system"
delay_seconds = 1

[ui.sound]
enabled = true

[experimental]
pane_history = true
resume_agents_on_restore = true
